# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nokit-machine-learning',
                'doc_host': 'https://apstrand.github.io',
                'git_url': 'https://github.com/apstrand/nokit-machine-learning',
                'lib_path': 'nokit_machine_learning'},
  'syms': {'nokit_machine_learning.core': {'nokit_machine_learning.core.foo': ('core.html#foo', 'nokit_machine_learning/core.py')}}}
